package client

import (
	"encoding/json"
	"fmt"
	"io"
)

// WriteFormatList writes a deterministic human-readable format table.
func WriteFormatList(w io.Writer, info *VideoInfo) error {
	if info == nil {
		return fmt.Errorf("%w: missing video info", ErrInvalidInput)
	}
	if _, err := fmt.Fprintf(w, "Title: %s\n", info.Title); err != nil {
		return err
	}
	if _, err := fmt.Fprintln(w, "ID | Ext | Resolution | FPS | Bitrate | Proto | Codec | Note"); err != nil {
		return err
	}
	if _, err := fmt.Fprintln(w, "---|-----|------------|-----|---------|-------|-------|------"); err != nil {
		return err
	}
	for _, f := range info.Formats {
		if _, err := fmt.Fprintln(w, formatListRow(f)); err != nil {
			return err
		}
	}
	return nil
}

func formatListRow(f FormatInfo) string {
	return fmt.Sprintf("%3d|%4s|%4dx%-4d|%3d|%6dk|%5s|%s|%s",
		f.Itag, FormatMediaExt(f.MimeType), f.Width, f.Height, f.FPS, f.Bitrate/1000, f.Protocol, f.MimeType, FormatTrackNote(f))
}

// WriteSubtitleTrackList writes available subtitle tracks.
func WriteSubtitleTrackList(w io.Writer, info *VideoInfo, tracks []SubtitleTrack) error {
	title := ""
	id := ""
	if info != nil {
		title = info.Title
		id = info.ID
	}
	if _, err := fmt.Fprintf(w, "Available subtitles for %s [%s]\n", title, id); err != nil {
		return err
	}
	if _, err := fmt.Fprintln(w, "lang|name|ext|kind"); err != nil {
		return err
	}
	for _, track := range tracks {
		kind := "manual"
		if track.AutoGenerated {
			kind = "auto"
		}
		ext := track.Ext
		if ext == "" {
			ext = "vtt"
		}
		if _, err := fmt.Fprintf(w, "%s|%s|%s|%s\n", track.LanguageCode, track.Name, ext, kind); err != nil {
			return err
		}
	}
	return nil
}

// WriteFlatPlaylist writes deterministic flat playlist output.
func WriteFlatPlaylist(w io.Writer, items []PlaylistItem, jsonMode bool) error {
	if jsonMode {
		enc := json.NewEncoder(w)
		for _, item := range items {
			payload := map[string]any{
				"_type": "url",
				"id":    item.VideoID,
				"title": item.Title,
				"url":   "https://www.youtube.com/watch?v=" + item.VideoID,
			}
			if err := enc.Encode(payload); err != nil {
				return err
			}
		}
		return nil
	}
	for _, item := range items {
		if _, err := fmt.Fprintf(w, "[flat] %s\t%s\n", item.VideoID, item.Title); err != nil {
			return err
		}
	}
	return nil
}
