package client

import (
	"bytes"
	"encoding/json"
	"strings"
	"testing"
)

func TestWriteFormatList(t *testing.T) {
	var buf bytes.Buffer
	err := WriteFormatList(&buf, &VideoInfo{
		ID:    "jNQXAC9IVRw",
		Title: "Example",
		Formats: []FormatInfo{
			{Itag: 18, MimeType: "video/mp4", HasAudio: true, HasVideo: true, Width: 640, Height: 360},
		},
	})
	if err != nil {
		t.Fatalf("WriteFormatList() error = %v", err)
	}
	out := buf.String()
	if !strings.Contains(out, "Title: Example") || !strings.Contains(out, "18| mp4| 640x360") {
		t.Fatalf("unexpected format list:\n%s", out)
	}
}

func TestWriteSubtitleTrackList(t *testing.T) {
	var buf bytes.Buffer
	err := WriteSubtitleTrackList(&buf, &VideoInfo{ID: "jNQXAC9IVRw", Title: "Example"}, []SubtitleTrack{
		{LanguageCode: "en", Name: "English", Ext: "vtt"},
		{LanguageCode: "ko", Name: "Korean", AutoGenerated: true},
	})
	if err != nil {
		t.Fatalf("WriteSubtitleTrackList() error = %v", err)
	}
	out := buf.String()
	for _, want := range []string{"Available subtitles for Example [jNQXAC9IVRw]", "en|English|vtt|manual", "ko|Korean|vtt|auto"} {
		if !strings.Contains(out, want) {
			t.Fatalf("subtitle list missing %q in:\n%s", want, out)
		}
	}
}

func TestWriteFlatPlaylistJSON(t *testing.T) {
	var buf bytes.Buffer
	err := WriteFlatPlaylist(&buf, []PlaylistItem{{VideoID: "jNQXAC9IVRw", Title: "one"}}, true)
	if err != nil {
		t.Fatalf("WriteFlatPlaylist() error = %v", err)
	}
	var payload map[string]any
	if err := json.Unmarshal(bytes.TrimSpace(buf.Bytes()), &payload); err != nil {
		t.Fatalf("json.Unmarshal() error = %v", err)
	}
	if payload["_type"] != "url" || payload["url"] != "https://www.youtube.com/watch?v=jNQXAC9IVRw" {
		t.Fatalf("payload=%v", payload)
	}
}
