package client

import "testing"

func TestParseSubtitleLanguagesAndExclusions(t *testing.T) {
	parsed := ParseSubtitleLanguages("ko, en,ko,-en,  ")
	wantParsed := []string{"ko", "en", "-en"}
	if len(parsed) != len(wantParsed) {
		t.Fatalf("parsed len=%d, want %d: %v", len(parsed), len(wantParsed), parsed)
	}
	for i := range wantParsed {
		if parsed[i] != wantParsed[i] {
			t.Fatalf("parsed[%d]=%q, want %q", i, parsed[i], wantParsed[i])
		}
	}
	applied := ApplySubtitleLanguageExclusions(parsed)
	if len(applied) != 1 || applied[0] != "ko" {
		t.Fatalf("ApplySubtitleLanguageExclusions()=%v, want [ko]", applied)
	}
}

func TestSubtitleLanguagesFromTracksForRequest(t *testing.T) {
	tracks := []SubtitleTrack{
		{LanguageCode: "en", AutoGenerated: false},
		{LanguageCode: "ko", AutoGenerated: false},
		{LanguageCode: "en", AutoGenerated: true},
		{LanguageCode: "live_chat", AutoGenerated: true},
	}
	manual := SubtitleLanguagesFromTracks(tracks, SubtitleLanguageSelection{IncludeManual: true})
	if len(manual) != 2 || manual[0] != "en" || manual[1] != "ko" {
		t.Fatalf("manual=%v, want [en ko]", manual)
	}
	auto := SubtitleLanguagesFromTracksForRequest(tracks, []string{"all", "-live_chat"}, SubtitleLanguageSelection{IncludeAuto: true})
	if len(auto) != 1 || auto[0] != "en" {
		t.Fatalf("auto=%v, want [en]", auto)
	}
	if !SubtitleLanguagesRequestAll([]string{"ko", "all", "-live_chat"}) {
		t.Fatalf("SubtitleLanguagesRequestAll()=false, want true")
	}
}
