package client

import "strings"

// SubtitleLanguageSelection controls subtitle language expansion from tracks.
type SubtitleLanguageSelection struct {
	IncludeManual bool
	IncludeAuto   bool
}

// ParseSubtitleLanguages parses a comma-separated subtitle language expression.
func ParseSubtitleLanguages(raw string) []string {
	parts := strings.Split(raw, ",")
	out := make([]string, 0, len(parts))
	seen := make(map[string]struct{}, len(parts))
	for _, part := range parts {
		lang := strings.ToLower(strings.TrimSpace(part))
		if lang == "" {
			continue
		}
		if _, ok := seen[lang]; ok {
			continue
		}
		seen[lang] = struct{}{}
		out = append(out, lang)
	}
	return out
}

// SubtitleLanguagesRequestAll reports whether a language expression contains all.
func SubtitleLanguagesRequestAll(langs []string) bool {
	for _, lang := range langs {
		if strings.EqualFold(strings.TrimSpace(lang), "all") {
			return true
		}
	}
	return false
}

// ApplySubtitleLanguageExclusions removes negative language selectors.
func ApplySubtitleLanguageExclusions(langs []string) []string {
	excluded := subtitleLanguageExclusions(langs)
	out := make([]string, 0, len(langs))
	seen := make(map[string]struct{}, len(langs))
	for _, lang := range langs {
		lang = strings.ToLower(strings.TrimSpace(lang))
		if lang == "" || strings.HasPrefix(lang, "-") {
			continue
		}
		if _, ok := excluded[lang]; ok {
			continue
		}
		if _, ok := seen[lang]; ok {
			continue
		}
		seen[lang] = struct{}{}
		out = append(out, lang)
	}
	return out
}

// SubtitleLanguagesFromTracksForRequest expands all/exclusion expressions against tracks.
func SubtitleLanguagesFromTracksForRequest(tracks []SubtitleTrack, requested []string, selection SubtitleLanguageSelection) []string {
	langs := SubtitleLanguagesFromTracks(tracks, selection)
	excluded := subtitleLanguageExclusions(requested)
	if len(excluded) == 0 {
		return langs
	}
	out := make([]string, 0, len(langs))
	for _, lang := range langs {
		if _, ok := excluded[strings.ToLower(strings.TrimSpace(lang))]; ok {
			continue
		}
		out = append(out, lang)
	}
	return out
}

// SubtitleLanguagesFromTracks selects unique language codes from tracks.
func SubtitleLanguagesFromTracks(tracks []SubtitleTrack, selection SubtitleLanguageSelection) []string {
	includeManual := selection.IncludeManual
	includeAuto := selection.IncludeAuto
	if !includeManual && !includeAuto {
		includeManual = true
	}
	langs := make([]string, 0, len(tracks))
	seen := make(map[string]struct{}, len(tracks))
	for _, track := range tracks {
		if track.AutoGenerated {
			if !includeAuto {
				continue
			}
		} else if !includeManual {
			continue
		}
		lang := strings.ToLower(strings.TrimSpace(track.LanguageCode))
		if lang == "" {
			continue
		}
		if _, ok := seen[lang]; ok {
			continue
		}
		seen[lang] = struct{}{}
		langs = append(langs, lang)
	}
	return langs
}

func subtitleLanguageExclusions(langs []string) map[string]struct{} {
	out := make(map[string]struct{})
	for _, lang := range langs {
		lang = strings.ToLower(strings.TrimSpace(lang))
		if strings.HasPrefix(lang, "-") && len(lang) > 1 {
			out[strings.TrimPrefix(lang, "-")] = struct{}{}
		}
	}
	return out
}
