package client

import "github.com/famomatic/ytv1/internal/types"

// VideoInfo is the package-level metadata result.
type VideoInfo struct {
	ID              string
	Title           string
	Author          string
	Description     string
	DurationSec     int64
	ViewCount       int64
	ChannelID       string
	PublishDate     string
	UploadDate      string
	Category        string
	IsLive          bool
	Keywords        []string
	ThumbnailURL    string
	ThumbnailWidth  int
	ThumbnailHeight int
	Formats         []FormatInfo
	DashManifestURL string
	HLSManifestURL  string
}

// FormatInfo is the normalized public format model.
type FormatInfo = types.FormatInfo

// SubtitleTrack describes one subtitle/caption track.
type SubtitleTrack struct {
	LanguageCode  string
	Name          string
	BaseURL       string
	VssID         string
	Kind          string
	AutoGenerated bool
	Ext           string
}

// TranscriptEntry is one timed caption segment.
type TranscriptEntry struct {
	StartSec float64
	DurSec   float64
	Text     string
}

// Transcript is a normalized transcript payload.
type Transcript struct {
	VideoID       string
	LanguageCode  string
	Name          string
	AutoGenerated bool
	SourceTrack   SubtitleTrack
	Entries       []TranscriptEntry
}

// PlaylistItem is one entry in a playlist.
type PlaylistItem struct {
	VideoID         string
	Title           string
	Author          string
	DurationSeconds string
	DurationSec     int64
	PlaylistIndex   int
}

// PlaylistContinuationWarning describes a non-fatal continuation traversal issue.
type PlaylistContinuationWarning struct {
	Token      string
	Reason     string
	HTTPStatus int
}

// PlaylistContinuationStats summarizes continuation traversal behavior.
type PlaylistContinuationStats struct {
	Requested        int
	Succeeded        int
	Failed           int
	SkippedDuplicate int
	SkippedEmpty     int
	StoppedByLimit   bool
}

// PlaylistInfo is a normalized playlist payload.
type PlaylistInfo struct {
	ID                   string
	Title                string
	Uploader             string
	UploaderID           string
	Channel              string
	ChannelID            string
	Items                []PlaylistItem
	ContinuationWarnings []PlaylistContinuationWarning
	ContinuationStats    PlaylistContinuationStats
}
