package cookies

import (
	"strings"
	"testing"
)

func TestParseNetscape(t *testing.T) {
	input := `# Netscape HTTP Cookie File
# This file is generated by a tool
.youtube.com	TRUE	/	TRUE	1999999999	VISITOR_INFO1_LIVE	abcdef12345
.google.com	TRUE	/	FALSE	1999999999	PREF	f1=50000000
`
	r := strings.NewReader(input)
	cookies, err := ParseNetscape(r)
	if err != nil {
		t.Fatalf("ParseNetscape() error = %v", err)
	}

	if len(cookies) != 2 {
		t.Fatalf("expected 2 cookies, got %d", len(cookies))
	}

	c1 := cookies[0]
	if c1.Name != "VISITOR_INFO1_LIVE" {
		t.Errorf("c1.Name = %q", c1.Name)
	}
	if c1.Value != "abcdef12345" {
		t.Errorf("c1.Value = %q", c1.Value)
	}
	if c1.Domain != ".youtube.com" {
		t.Errorf("c1.Domain = %q", c1.Domain)
	}
	if !c1.Secure {
		t.Error("c1.Secure should be true")
	}
	if c1.Expires.Unix() != 1999999999 {
		t.Errorf("c1.Expires = %d", c1.Expires.Unix())
	}

	c2 := cookies[1]
	if c2.Name != "PREF" {
		t.Errorf("c2.Name = %q", c2.Name)
	}
	if c2.Secure {
		t.Error("c2.Secure should be false")
	}
}
